# Generated by Django 2.2.1 on 2019-05-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun_nome', models.CharField(max_length=45)),
                ('fun_sobrenome', models.CharField(max_length=45)),
                ('fun_cpf', models.CharField(max_length=14)),
                ('fun_salario', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
